const UTC = [
  'UTC -12',
  'UTC -11',
  'UTC -10',
  'UTC -9',
  'UTC -9:30',
  'UTC -9',
  'UTC -8 (ex, California)',
  'UTC -7 (ex, Colorado)',
  'UTC -6 (ex, Texas)',
  'UTC -5 (ex, New York)',
  'UTC -4',
  'UTC -3',
  'UTC -2',
  'UTC -1',
  'UTC 0 (ex, Ireland)',
  'UTC +1 (ex, Denmark)',
  'UTC +2 (ex, Greece)',
  'UTC +3',
  'UTC +4',
  'UTC +4:30',
  'UTC +5',
  'UTC +5:30 (ex, India)',
  'UTC +6',
  'UTC +6:30',
  'UTC +7 (ex, Thailand)',
  'UTC +8 (ex, China)',
  'UTC +9 (ex, Japan)',
  'UTC +10',
  'UTC +11',
  'UTC +12',
  'UTC +13',
  'UTC +14',
]

export default UTC;